schema_version = "1.0.0"

id = "t4p_clean"
version = "0.1.0"
name = "T4P clean"
tagline = "Clean bad geometry to prepare for further boolean."
type = "add-on"

maintainer = "Markus Kruse"

blender_version_min = "4.5.0"

license = ["GPL-3.0-or-later"]

